### ISSUE TITLE
Unable to run W32, I get a System.ArgumentOutOfRangeException: on Version 1.8.5

### ISSUE THREAD

**Issue by cu-ri-os-i-ty** [microsoft/Microsoft-Win32-Content-Prep-Tool#121]
Running Windows 11 PowerShell as Administrator
Edition	Windows 11 Enterprise
Version	23H2
Installed on	‎9/‎3/‎2023
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

ERROR  System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 57.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLine(AppContext context, String text)   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

**Comment by modernworkspace** [comment]
i have the same error if the source contains only msi file.
i just add a empty text file in source folder and the win32app is create

**Comment by stephen-lewis** [comment]
I get a similar error in 1.8.6:

```
INFO   Calculated size for folder 'Src' is 10183778310 within 202 milliseconds
INFO   Compressed folder 'Src' successfully within 503964 milliseconds
INFO   Removing temporary files
ERROR  System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: sourceTop
Actual value was 100.
   at System.Console.MoveBufferArea(Int32 sourceLeft, Int32 sourceTop, Int32 sourceWidth, Int32 sourceHeight, Int32 targetLeft, Int32 targetTop, Char sourceChar, ConsoleColor sourceForeColor, ConsoleColor sourceBackColor)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLine(AppContext context, String text)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

Happens at the end of the process, and looks like it's just a console output error, but it prevents the package being created.

Running in cmd in Windows Terminal 1.20.11781.0, on Win11 pro 23H2, build 22631.4037.

**Comment by ameltzer-MSFT** [comment]
#111
