### ISSUE TITLE
Fail to generate intunewin file - System.IO.InvalidDataException

### ISSUE THREAD

**Issue by alamport-davey** [microsoft/Microsoft-Win32-Content-Prep-Tool#127]
Every time I try to run this tool with this file I get the following errors;

ERROR File 'C:\temp\OUT\solidworks.intunewin'  has failed to be generated

ERROR System.IO.InvalidDataException: Invalid ALLUSERS property value: 0
    at Microsoft.Management.Service.IntuneWinAppUtil.MsiUtil.ReadApplicationInfo(String contentFile)
    at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String output Folder, String catalogFolder)
    at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

And then it just crashes.

See screenshot below

![Screenshot (3)](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/173115938/14076ef0-7fcd-4775-b36f-4c74b120323c)

**Comment by ameltzer-MSFT** [comment]
Thank you for reporting this issue. Is this a publicly available MSI? If so, could you provide a download link so we can try to reproduce internally.

**Comment by ameltzer-MSFT** [comment]
Looking more closely at the error text, it appears this is by design. The tool only supports one of the following combinations of the ALLUSERS property:
* <not set>, <null>, or <empty>: User install context
* 1: System install context
* 2: User or System install context

It looks like the specific MSI you're using has an ALLUSERS value of "0", which causes the tool to fail as it is unable to determine what the installation context of the application should be.

This is consistent with the documentation: https://learn.microsoft.com/en-us/windows/win32/msi/allusers
