### ISSUE TITLE
System.IO.InvalidDataException: Entries larger than 4GB

### ISSUE THREAD

**Issue by lounsberry** [microsoft/Microsoft-Win32-Content-Prep-Tool#134]
When trying to run this utility, I am getting this error message:

```
ERROR  System.IO.InvalidDataException: Entries larger than 4GB are not supported in Update mode.
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, ReportProgress reportProgress, Boolean useExistingZipFile)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.ZipFolder(String folder, String zipFile, AppContext context, Boolean noCompression, Boolean includeBaseDirectory, Boolean appendFile, Boolean useExistingZipFile)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

I'm using version 1.8.6.0 and the total size of the files in the folder are only 2.87 GB in Windows, so I'm not quite sure where it's getting the 4GB error from. I do see the log entry immediately before it starts removing temp files:

`INFO    Calculated size for folder <...> is 3084957570 within 4 milliseconds`

**Comment by Rustamus82** [comment]
Same here, I am to package 3,3 GB and getting same error with Microsoft-Win32-Content-Prep-Tool-1.8.6:
...\Deploy-Application.intunewin' has failed to be generated


[================                                 ]   32%                                                               INFO   Done!!!

ERROR  System.IO.InvalidDataException: Poster større end 4 GB understøttes ikke i opdateringstilstand.
   ved System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   ved System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   ved Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, ReportProgress reportProgress, Boolean useExistingZipFile)
   ved Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.ZipFolder(String folder, String zipFile, AppContext context, Boolean noCompression, Boolean includeBaseDirectory, Boolean appendFile, Boolean useExistingZipFile)
   ved Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   ved Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

**Comment by satishtiwary** [comment]
Hi Team,

We are also encountering this issue in our enterprise environment when packaging large applications (>4GB) using the Microsoft Win32 Content Prep Tool.

Details:
- Intune (Windows Autopatch environment)
- Application sizes exceeding 4GB
- Error observed: System.IO.InvalidDataException – Entries larger than 4GB

From our testing:
- The issue appears consistently when packaging large payloads
- Smaller packages work without issue

Questions:
1. Is there a documented limit for .intunewin package size?
2. Is this a limitation of the packaging tool (ZIP format / 4GB boundary)?
3. Are there any supported workarounds or recommended approaches for large applications?

Impact:
This is blocking deployment of large enterprise applications through Intune.

Any guidance or confirmation would be appreciated.

Thanks,
Satish

**Comment by svrooij** [comment]
> [Open-source alternative](https://www.powershellgallery.com/packages/SvRooij.ContentPrep.Cmdlet/)

There is an open-source module that does not have this limit. I think it is also fixed in the latest version the official tool.

Are you sure it is not a memory problem? Or are you putting the file on a device that does not support files bigger then 4gb?
