### ISSUE TITLE
System.ArgumentOutOfRangeException - well known issue

### ISSUE THREAD

**Issue by nookyang** [microsoft/Microsoft-Win32-Content-Prep-Tool#29]
.\IntuneWinAppUtil -c C:\Temp\Azure\RawApps\FortiClient -s FortiClientSSO.msi -o 123 -q

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 3074.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLine(AppContext context, String text)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

When it will be fixed?

**Comment by Ellestad1995** [comment]
I'm also experiencing this issue. I'm packing a software as part of a build script and need to execute IntuneWinAppUtil.exe as part of a Powershell script.
Like so
```
& $IntuneWinAppUtil -c $BuildPath -s $InstallationFilePath -o $BuildPath
```
This causes the error mentioned in this issue. 

To fix this it is possible to `Clear-Host` before the execution.

```
Clear-Host
& $IntuneWinAppUtil -c $BuildPath -s $InstallationFilePath -o $BuildPath
```
This obviously causes the earlier printout in the terminal to be dismissed.
And i would like to keep the output in the terminal for troubleshooting reasons.

Is it really necessary to have the fancy printout that causes this bug?

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 127.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLine(AppContext context, String text)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```
 
![image](https://user-images.githubusercontent.com/16270816/77178511-76a85180-6ac7-11ea-8949-0ef63d25244d.png)

**Comment by Skatterbrainz** [comment]
I'm getting this same error with "Actual value was 59." - running on Windows 10 Enterprise 64-bit build 10.0.19041
