### ISSUE TITLE
Error for Windows Platform FIPS

### ISSUE THREAD

**Issue by nathanaelad** [microsoft/Microsoft-Win32-Content-Prep-Tool#33]
No matter how I run this application I keep getting the below error. 

```
File 'Build\SummerSausage.intunewin' has faield to be generated


[===============================                  ]   61%                                                               Done!!!

System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA256Managed..ctor()
   at Microsoft.Management.Service.IntuneWinAppUtil.EncryptUtil.EncryptFile(String file, AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

The most related issue I can find so far is is [this post on stackoverflow](https://stackoverflow.com/questions/14509354/this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptogra). The suggested registry changed do not seem to work, unfortunately.

**Comment by Robert-Wint** [comment]
Getting the same error. and I have tried on 4 different computers. still cant get a resolution. I even tried the registry hack still a no go. I have used this when it just came out and it worked perfectly, now it doe snot work any more.

**Comment by nathank1989** [comment]
I had success, in my testing, using this tool to compile a package inside of Windows Sandbox. Some AzureAD Policy on my workstation has enabled FIPS and used the Sandbox to compile my one app using the tool successfully.

**Comment by djatw0rk123** [comment]
Any updates on validating this app?

**Comment by argjesse** [comment]
Found a workable solution:
1) open Local Security Policy ; 
navigate to Security Settings > Local Policies > Security Options > System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing ; 
Disable it 
2) open regedit ; 
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy ; 
change both values "Enabled" and "MDMEnabled" to 0 

worked for me after making the above changes

**Comment by Robert-Wint** [comment]
This worked for me too. Although the only thing I had to disable was MDMenabled as it was the only setting set to enabled.
Thank you for the fix

**Comment by garrett-wood** [comment]
For those of us who can't "just disable" FIPS mode, this is an ongoing issue. Can this be updated to use FIPS crypto?

**Comment by alexbuzzbee** [comment]
I'm currently disabling FIPS mode enforcement in `machine.config` each time I run this. I hope it's obvious that having to do that isn't optimal.

**Comment by renemp** [comment]
> Found a workable solution:
> 
> 1. open Local Security Policy ;
>    navigate to Security Settings > Local Policies > Security Options > System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing ;
>    Disable it
> 2. open regedit ;
>    Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy ;
>    change both values "Enabled" and "MDMEnabled" to 0
> 
> worked for me after making the above changes

stting "MDMEnabled" to 0 is enough. No need te reboot.

**Comment by bdoeax** [comment]
This really needs the correct fix.  Our policies require FIPS and I shouldn't need to disable that just to add apps to Intune, even temporarily.  If it's really a single line that needs changing can we get an update?

**Comment by ColoradoITGuy** [comment]
Ran into this today. With more and more people moving to CIS and other standards that require FIPS this is going to be coming up more often. Would love to see a fix ASAP.

**Comment by jtichenor75** [comment]
I had been using the workaround to change Enabled and MDMEnabled in the registry to 0. That was working just fine until installing Bitlocker with FIPS mode enabled. After Bitlocker has been installed, even with that registry change, the utility still squawks about not being FIPS compliant. So, it is 100% useless to me at this point. Please release a FIPS-compliant version.

**Comment by cbiliti** [comment]
Any updates on this issue? Still struggling with the Bitlocker FIPS..

**Comment by ashek-simeon** [comment]
Hello @A9G-Data-Droid. I'm an engineer at a company named Simeon Cloud. Our team has created an open source tool [http://github.com/simeoncloud/IntuneAppBuilder/](https://github.com/simeoncloud/IntuneAppBuilder/) which has the same functionality as this tool (plus the ability to publish apps). Maybe it could be a viable alternative for you.

**Comment by GoodThings2Life** [comment]
Ah the irony of Microsoft requiring use of a tool they won't even support to make a single line change and then having the nerve to put the download on GitHub without also posting the source code for the tool. It's almost as if they only pay lip service to open source initiatives...

Anyway, here to say I just ran into this same issue. Thankfully, I _do_ have the option to override the policy, but still not ideal.

**Comment by A9G-Data-Droid** [comment]
A new version was released without source code, so I had to test it to find if this was fixed. Same error. They didn't change the one line of code needed to close this issue. It's not even a breaking change. They are using SHA256, which is fine! If you use the FIPS compatible version of SHA256 you will get the same hash values. It will "just work".

**Comment by TonnyWildeman** [comment]
I don't have FIPS enabled. But did have the same symptoms. 
Running the tool totally crashed my Terminal window. Took a video and saw the exception flashing by just before the window closing.

Added Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy\MDMEnabled DWord (32 bit) = 0 registry entry and it worked...miraculously.

**Comment by A9G-Data-Droid** [comment]
> MDMEnabled DWord (32 bit) = 0 registry entry and it worked...miraculously.

@TonnyWildeman Do you work for the federal government or a contractor bound to comply with FIPS?

If so, turning off that setting is a policy violation. You should speak with your security team to find out why that setting is enabled and ask if it's safe to turn it off. Your PC will begin to show up on audit reports. If you have a regular IT process that requires a security violation to function you'll never be compliant.

[Microsoft's approach to FIPS 140-2 validation](https://learn.microsoft.com/en-us/windows/security/security-foundations/certification/fips-140-validation#microsofts-approach-to-fips-140-2-validation)

> Microsoft maintains an active commitment to meeting the requirements of the FIPS 140-2 standard, having validated cryptographic modules against it since it was first established in 2001. Microsoft validates its cryptographic modules under the NIST CMVP, as described above. Multiple Microsoft products, including Windows 10, Windows Server, and many cloud services, use these cryptographic modules.

**Comment by TonnyWildeman** [comment]
@A9G-Data-Droid I do not work for or in the USA. Most people don't.

And people may be compliant in the USA, if they use the prep tool in a Windows Sandbox as suggested by @nathank1989.

**Comment by A9G-Data-Droid** [comment]
@TonnyWildeman Then you absolutely should not be using FIPS mode. Then next question is then about how that setting got applied to your computer. You wouldn't want that being pushed to your organization.

**Comment by GoodThings2Life** [comment]
> @TonnyWildeman Then you absolutely should not be using FIPS mode. Then next question is then about how that setting got applied to your computer. You wouldn't want that being pushed to your organization.

I don't mean to be rude, but you seem to be missing the point of this thread. The point is that the tool does not work correctly when FIPS mode is enabled which is a requirement for many of us. Why we have it enabled is really not the concern. The concern is that if we do, the tool doesn't work, and a solution has been proposed, but nobody at Microsoft seems to be listening.

**Comment by silver0a1** [comment]
Still having this issue as of Feb 2024.

**Comment by neo42man** [comment]
We are also facing this issue. 
Since it is not an option for us to customize policies or registry keys we searched for another workaround.

When you add a IntuneWinAppUtil.exe.config file next to the IntuneWinAppUtil.exe you can disable the FIPS checks just for this executeable.  Content for the .config file:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<runtime>
        <enforceFIPSPolicy enabled="false"/>
	</runtime>
</configuration>`

**Comment by ITGUY098** [comment]
> We are also facing this issue. Since it is not an option for us to customize policies or registry keys we searched for another workaround.
> 
> When you add a IntuneWinAppUtil.exe.config file next to the IntuneWinAppUtil.exe you can disable the FIPS checks just for this executeable. Content for the .config file:
> 
> `<?xml version="1.0" encoding="utf-8"?> <configuration> <runtime> <enforceFIPSPolicy enabled="false"/> </runtime> </configuration>`

How are you adding the config file next to the exe?

**Comment by jason-dawnbreaktech** [comment]
This is a critical issue. I cannot disable FIPS mode in my environment. Please update the tool to use the FIPS compatible version of SHA256. I don't want to have to maintain an air gapped sandbox to run a packaging utility 😕

**Comment by radiant-flux** [comment]
I can't believe this has been discussed for 5 years and hasn't been implemented yet. Working at a company in the GCC cloud, we never would have moved to M365 if we knew so many essential features were just not available for us.
Seriously, if your company requires FIPS, you just don't have the option of packaging up apps for Intune? It's completely absurd.

**Comment by djatw0rk123** [comment]
[like]  Johnson, David reacted to your message:
________________________________

**Comment by ameltzer-MSFT** [comment]
FIPS support has been added into the latest release
