### ISSUE TITLE
Using catalogs folders results in IOException

### ISSUE THREAD

**Issue by lcostantino** [microsoft/Microsoft-Win32-Content-Prep-Tool#34]
Trying to add catalogs for Windows 10S for 7zip it's raising IOException.
If i remove the catalog dir argument it works ok.

C:\ppp\Microsoft-Win32-Content-Prep-Tool-master>IntuneWinAppUtil.exe  -s 7zip\exe\7z1900-x64.exe -a 7zip\cats\ -o s

Validating parameters
Validated parameters with 37 milliseconds
Compressing the catalog folder '7zip\cats\' to 'C:\Users\admin\AppData\Local\Temp\212aa682-3a19-4f84-99cc-94f2b03d218b\IntuneWinPackage\Contents\IntunePackage.intunewin'
Max index for catalog prefix search is -1.
Copying catalog files from 7zip\cats\ to C:\Users\admin\AppData\Local\Temp\18316671-2f68-4d02-9125-9d114d9685b6\Cat_C029B285-222F-460B-8ECA-2CD7A8A424B7.
Copying catalog file from 7zip\cats\7z1900-x64.cat to C:\Users\admin\AppData\Local\Temp\18316671-2f68-4d02-9125-9d114d9685b6\Cat_C029B285-222F-460B-8ECA-2CD7A8A424B7\7z1900-x64.cat.
Copying catalog file from 7zip\cats\7z1900-x64.cdf to C:\Users\admin\AppData\Local\Temp\18316671-2f68-4d02-9125-9d114d9685b6\Cat_C029B285-222F-460B-8ECA-2CD7A8A424B7\7z1900-x64.cdf.
Copied catalog files from 7zip\cats\ to C:\Users\admin\AppData\Local\Temp\18316671-2f68-4d02-9125-9d114d9685b6\Cat_C029B285-222F-460B-8ECA-2CD7A8A424B7. with 55 milliseconds
Calculated size for folder 'C:\Users\admin\AppData\Local\Temp\18316671-2f68-4d02-9125-9d114d9685b6\Cat_C029B285-222F-460B-8ECA-2CD7A8A424B7' is 2062 with 2 milliseconds
Compressed folder 'C:\Users\admin\AppData\Local\Temp\18316671-2f68-4d02-9125-9d114d9685b6\Cat_C029B285-222F-460B-8ECA-2CD7A8A424B7' successfully with 127 milliseconds
Compressing the souce folder '7zip\exe' to 'C:\Users\admin\AppData\Local\Temp\212aa682-3a19-4f84-99cc-94f2b03d218b\IntuneWinPackage\Contents\IntunePackage.intunewin'
Calculated size for folder '7zip\exe' is 1447178 with 0 milliseconds
Removing temporary files
Removed temporary files with 15 milliseconds
File 's\7z1900-x64.intunewin' has faield to be generated

System.IO.IOException: The file 'C:\Users\admin\AppData\Local\Temp\69954d04-1cff-430a-a365-7d1bb8b237d3\IntuneWinPackage\Contents\IntunePackage.intunewin' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, ReportProgress reportProgress)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.ZipFolder(String folder, String zipFile, AppContext context, Boolean noCompression, Boolean includeBaseDirectory, Boolean appendFile)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

**Comment by lcostantino** [comment]
It works ok with 1.6 but fails in 1.7

**Comment by UniverseCitiz3n** [comment]
Any updates on that? New version comes out but this is still not fixed :(

**Comment by zuhairm2000** [comment]
I am having the same issue, has it been fixed?

regards

**Comment by smurph8875** [comment]
I don't think it has been fixed, but works perfectly if you download v1.7 from the Versions on GitHub

**Comment by persalmi** [comment]
I got this same error on 1.8.2 on Windows 10 x64. Any fix or workaround available?

**Comment by computerdave** [comment]
Same problem here, had to go all the way back to v1.6 to get it to complete successfully.

**Comment by ameltzer-MSFT** [comment]
Is this issue still occurring with the latest release of the tool? If it is, could you please attach repro files so we can investgiate? Thanks!

**Comment by ameltzer-MSFT** [comment]
Unable to reproduce this
