### ISSUE TITLE
Access to the path 'IntunePackage.intunewin' is denied

### ISSUE THREAD

**Issue by josephgibbs** [microsoft/Microsoft-Win32-Content-Prep-Tool#67]
I receive the following error when attempting to create a driver installation package. This seems to happen when there are zip files included in the source folder.

`ERROR  System.UnauthorizedAccessException: Access to the path 'IntunePackage.intunewin' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)`

**Comment by ameltzer-MSFT** [comment]
If this is still occurring, please reopen and provide a repro package if possible.

**Comment by dkneisz** [comment]
I still have this issue e.g. when trying this with Notepad++ (v8.7 in my case). The output is:
```
INFO   Computed SHA256 hash for 'C:\Users\<user>\AppData\Local\Temp\6ffb452b-4e08-4528-b6d4-38b4936b18ae\IntuneWinPackage\Contents\cef925a8-ce7a-4d97-ad72-d5825090ef0e' within 61 milliseconds
INFO   Computing SHA256 hash for C:\Users\<user>\AppData\Local\Temp\6ffb452b-4e08-4528-b6d4-38b4936b18ae\IntuneWinPackage\Contents\IntunePackage.intunewin
INFO   Computed SHA256 hash for C:\Users\<user>\AppData\Local\Temp\6ffb452b-4e08-4528-b6d4-38b4936b18ae\IntuneWinPackage\Contents\IntunePackage.intunewin within 63 milliseconds
INFO   Copying encrypted file from 'C:\Users\<user>\AppData\Local\Temp\6ffb452b-4e08-4528-b6d4-38b4936b18ae\IntuneWinPackage\Contents\cef925a8-ce7a-4d97-ad72-d5825090ef0e' to 'C:\Users\<user>\AppData\Local\Temp\6ffb452b-4e08-4528-b6d4-38b4936b18ae\IntuneWinPackage\Contents\IntunePackage.intunewin'
INFO   Removing temporary files
ERROR  System.UnauthorizedAccessException: Access to the path 'IntunePackage.intunewin' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```
My guess is, that this is caused by the virus scanner / endpoint protection.  When I do the same on a device without virus scanner / endpoint protection it works. It looks like the IntuneWinAppUtil is trying to (re)move the file while the virus scanner / endpoint protection is still scanning the file. Maybe a solution could be to retry this operation a few times before throwing an error. In most cases people will not be able to deacitvate the virus scanner / endpoint protection to get around this.

**Comment by ameltzer-MSFT** [comment]
Thanks for the additional information! We can look into improving the error handling here. In this case, is it just cleanup that's failing and the intunewin is otherwise usable?

**Comment by dkneisz** [comment]
It is not just the cleanup that is failing. There is nothing created in the output folder. The mentioned IntunePackage.intunewin file in the temp folder does exist, but seems to be unusable. It does only contain the installer, but not the folder structure and other files the successful intunewin file has.

**Comment by ameltzer-MSFT** [comment]
Thanks for the additional information. I've opened a bug internally to track this and we will investigate further.

**Comment by dkneisz** [comment]
Is there an update on this? This should be a simple fix. Just wait a few seconds and retry it several times before throwing an error. It's getting annoying because I run into this issue with more apps and there is nothing I can do about it.
