### ISSUE TITLE
[version 1.5] 4GB File Size Limit?

### ISSUE THREAD

**Issue by TechTrooper** [microsoft/Microsoft-Win32-Content-Prep-Tool#9]
I'm unable to package a 5GB CAD software due to 4GB file size limit. None of the files inside the archive is above 2GB.

Intune win32 apps are supposed to support up to 8GB packages (according to [docs.microsoft.com](https://docs.microsoft.com/en-us/intune/apps-win32-app-management#prerequisites))
![image](https://user-images.githubusercontent.com/3955313/59927939-46ebf080-9446-11e9-8c9c-bbdf8d927b94.png)

`System.IO.InvalidDataException: Entries larger than 4GB are not supported in Update mode.
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, CompressionOption compressionOption, Boolean includeBaseDirectory, ReportProgress reportProgress)
   at Microsoft.Management.Service.IntuneWinAppUtil.ZipUtil.ZipFolder(String folder, String zipFile, AppContext context, Boolean noCompression, Boolean includeBaseDirectory)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)`

**Comment by TechTrooper** [comment]
Unsolved and unable to test with later versions. Closing
